# frozen_string_literal: true

source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-websocket'
gem 'oga'

group :develop do
  gem 'irb'
  gem 'rdoc'
  gem "google-apis-youtube_v3"
  gem 'test-unit'
  #gem "faye-websocket"
  gem 'websocket-client-simple'
end
